use_frameworks!

platform :ios, '9.0'

target 'SignalBus_Example' do
  pod 'SignalBus', :path => '../'

  target 'SignalBus_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
